name: Secure Config Update

on:
  schedule:
    - cron: '30 17 * * *'  # 9:00 PM Iran time (UTC+3:30)
  workflow_dispatch:  # Optional: allow manual runs

jobs:
  update-configs:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pycryptodome requests

      - name: Run hidden config script
        env:
          CONFIG_SCRIPT: ${{ secrets.CONFIG_SCRIPT }}
          GIST_ID: ${{ secrets.GIST_ID }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        run: |
          echo "$CONFIG_SCRIPT" > secure_script.py
          python secure_script.py
